### ISSUE TITLE
Dimensions mismatch

### ISSUE THREAD

**Issue by codeghees** [acheketa/cwavegan#2]
> ValueError: Dimensions must be equal, but are 16384 and 8202 for 'sub_1' (op: 'Sub') with input shapes: [64,16384,1], [64,8202,1].

>  File "gpu/train_wavegan.py", line 531, in <module>
    train(fps, args)
  File "gpu/train_wavegan.py", line 135, in train
    differences = G_z - x

I am getting this error - training on Google Speech SC09 dataset, like the paper.
What is the possible fix?

**Comment by chaeyoung-lee** [comment]
@codeghees  thank you for reporting this error.

I made a change to the code, and the dimension of both the G_z and x is 8192. Here is what I did to make this change.

### 1. Removed concatenation
```python3
x = tf.concat([x, y_fill], 1)
z = tf.concat([z, y], 1)
```
This made the dimension of x from [batch size, 8192, 1] to [batch size, 8202, 1]. I recommend the bias scaling method than this label concatenation method (meaningless conditioning), so just take this part out. Now, x dimension is [batch size, 8192, 1]

### 2. Modified output dim of G_z
```python3
output = conv1d_transpose(output, 1, kernel_len, 2, upsample=upsample)
```
I changed [this line](https://github.com/acheketa/cwavegan/blob/master/gpu/wavegan.py#L108) and now the output dimension of the generator is 8192 (half of 16384).

### 3. Bias scaling method
Now that I removed the concatenation based conditioning in the gpu implementaion, we need to implement the bias scaling method. Previously, only the tpu implementation used this method but now both use this method. This change is in `wavegan.py` file and in every convolution layer, I make a bias layer and scale it to the output layer through `tf_repeat` function defined [here](https://github.com/acheketa/cwavegan/blob/master/gpu/wavegan.py#L3). An example is
```python3
# wavegan.py line 73-79
# Layer 0
  # [16, 1024] -> [64, 512]
  with tf.variable_scope('upconv_0'):
    output = conv1d_transpose(output, dim * 8, kernel_len, 4, upsample=upsample)
    output = batchnorm(output)
  output = tf_repeat(output, labels, 64, dim * 8, bias)    # <--HERE!!
  output = tf.nn.relu(output)
```

Please let me know if you have errors, I'll help you solve it.

**Comment by codeghees** [comment]
Hey, thank you for replying!
The command I ran and the error I am getting. 
> python gpu/train_wavegan.py train ./gpu/train  --data_dir ./sc09
Traceback (most recent call last):
  File "gpu/train_wavegan.py", line 530, in <module>
    infer(args)
  File "gpu/train_wavegan.py", line 245, in infer
    G_z = WaveGANGenerator(z, train=False, **args.wavegan_g_kwargs)
TypeError: WaveGANGenerator() takes at least 2 arguments (6 given)

**Comment by chaeyoung-lee** [comment]
Change line 245.
```
G_z = WaveGANGenerator(z, y, train=False, **args.wavegan_g_kwargs)
```

I did a few experiments with the code, fixed a bit of input related lines. **Please pull the latest version of the code and redownload the sc09 tfrecord dataset.** You can either make your own tfrecord dataset with `make_tfrecord_int.py` or simply download my tfrecord dataset from this [link](https://drive.google.com/file/d/1yX5iFZ9sqaD4_9-OhmsISZ1PkDnGjHse/view?usp=sharing).

Let me know if you have any error.

**Comment by codeghees** [comment]
I ran the code again (after pulling and re-downloading the dataset).
The error that I got:
> NotFoundError (see above for traceback): Key D/downconv_0/conv1d/bias/Adam_1 not found in checkpoint
         [[Node: save/RestoreV2_2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_2/tensor_names, save/RestoreV2_2/shape_and_slices)]]

This came with a lot of warnings like:

> 2020-03-26 13:00:31.835142: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key D/downconv_4/conv1d/kernel/Adam not found in checkpoint
2020-03-26 13:00:31.836540: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key D/downconv_4/conv1d/kernel/Adam_1 not found in checkpoint
2020-03-26 13:00:31.837803: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key D/downconv_0/conv1d/bias/Adam_1 not found in checkpoint
         [[Node: save/RestoreV2_2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_2/tensor_names, save/RestoreV2_2/shape_and_slices)]]

My environment is an EC2 instance with Tesla K80. From what I understand, this seems like an error due to checkpointing. I am not passing any checkpoint since I am running the code for the first time.

Any idea how to fix this, apologies for repeated queries.

**Comment by chaeyoung-lee** [comment]
No worries. Can you copy the entire error including the traceback (and line number)? And can you check if you have any checkpoints saved in your log folder?

**Comment by codeghees** [comment]
I cleared my log folder and the code seems to be running. However, there is no output saying training has started. How long should I let it train to run the preview script? 
Ran the backup script as well.
Current output:
> 2020-03-26 14:34:29.226498: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 $
2020-03-26 14:34:29.305790: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA no$
2020-03-26 14:34:29.306460: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties:
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:00:1e.0
totalMemory: 11.17GiB freeMemory: 11.11GiB
2020-03-26 14:34:29.306482: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla K80, pci bus id: 0000:00:1e.0, co$

**Comment by codeghees** [comment]
Also I ran the preview script 

> python gpu/train_wavegan.py preview ./gpu/preview                                                                                                       
Traceback (most recent call last):
  File "gpu/train_wavegan.py", line 548, in <module>
    preview(args)
  File "gpu/train_wavegan.py", line 311, in preview
    saver = tf.train.import_meta_graph(infer_metagraph_fp)
  File "/home/ubuntu/anaconda3/envs/caffe_p27/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1803, in import_meta_graph
    meta_graph_def = meta_graph.read_meta_graph_file(meta_graph_or_file)
  File "/home/ubuntu/anaconda3/envs/caffe_p27/lib/python2.7/site-packages/tensorflow/python/framework/meta_graph.py", line 555, in read_meta_graph_file
    raise IOError("File %s does not exist." % filename)
IOError: File ./gpu/preview/infer/infer.meta does not exist.


Should I give it the path of ./gpu/train/infer because that is where I see the infer.met exisiting?

**Comment by codeghees** [comment]
I just looked at the requirements, is the code available for Python 3 now?

**Comment by codeghees** [comment]
I ran the preview script 

> python gpu/train_wavegan.py preview ./gpu/train
The error it gives:

> tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [100,16384] rhs shape= [90,16384]
         [[Node: save/Assign_11 = Assign[T=DT_FLOAT, _class=["loc:@G/z_project/dense/kernel"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](G/z_project/dense/kernel, save/RestoreV2_11/_23)]]


I am assuming some parameter needs fixing since it's a shape's mismatch. I am working through the code to see if I can find but if you could help it would be great. Thank you!

**Comment by chaeyoung-lee** [comment]
Yes, this code runs in both Python 2 and 3.

Pull the updated version of the code and run
```shell
python gpu/train_wavegan.py infer ./gpu/train
```

This will create a new meta graph. Then run preview mode
```shell
python gpu/train_wavegan.py preview ./gpu/train
```

Make sure to correctly put your training directory. The infer mode will call meta graph from `./gpu/train/infer` and the preview mode `./gpu/train/preview`. When you run `backup.py` and preview mode in the background, you can generate preview audio files every time a new checkpoint is saved.

When training, there is no upper bound in the iteration. This will keep running until you cancel the command. This is because it's hard to identify when the training is complete. Run `tensorboard` to monitor your losses, but you need to determine the training completion by listening to the preview audio files at every checkpoint. That is why this code runs the preview mode in the background.
